Portfolio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path , include
from jobs import views as jobs_views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', jobs_views.home, name='home'),
    path('blog/', include('blog.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path , include
from .views import *

app_name = 'blog'
urlpatterns = [

    path('blog_list', blog_list , name='blog_list'),
    path('blog_details/<int:blog_id>', blog_details , name='blog_details'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.


class Blog(models.Model):
    title = models.CharField(verbose_name='عنوان', max_length=255)
    pub_date = models.DateTimeField(verbose_name='تاریخ انتشار')
    body = models.TextField(verbose_name='متن')
    image = models.ImageField(verbose_name='تصویر', upload_to='images/')

    def body_summary(self):
        return self.body[:50]

    def pub_date_pretty(self):
        return self.pub_date.strftime("%Y-%m-%d %H:%M:%S")

    def __str__(self):
        return self.title

jobs/models.py
from django.db import models

# Create your models here.


class Job(models.Model):
    picture = models.ImageField(upload_to='images/' , verbose_name='تصویر')
    summary = models.CharField(verbose_name='توضیحات', max_length=300)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog


# Create your views here.


def blog_list(request):
    template_name = 'blog/blog_list.html'
    blogs = Blog.objects.all()
    context = {'blogs': blogs}
    return render(request, template_name, context)


def blog_details(request, blog_id):
    template_name = 'blog/blog_details.html'
    blog = get_object_or_404(Blog, pk=blog_id)
    print(blog)
    context = {'blog': blog}
    return render(request, template_name, context)

jobs/views.py
from django.shortcuts import render

# Create your views here.
from .models import Job


def home(request):
    template_name = 'jobs/home.html'

    jobs = Job.objects.all()

    context = {'jobs' : jobs}
    return render(request, template_name, context)

blog/templates/blog/blog_details.html
{% extends '_base.html' %}
{% load static %}

{% block content %}



<div class="container">
<div class="row mb-2">


    <div class="col-md-6">
      <div class="row">
        <div class="col p-4">
          <h1>{{ blog.title }}</h1>
          <div class="mb-1 text-muted">{{ blog.pub_date_pretty }}</div>
          <p class="card-text mb-auto">{{ blog.body }}</p>
          <img src="{{ blog.image.url }}" alt='تصویر' />

        </div>
        <br>
      </div>
    </div>



  </div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends '_base.html' %}
{% load static %}

{% block content %}



<div class="container">
<div class="row mb-2">




  {% for blog in blogs %}


    <div class="col-md-6">
      <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-primary">{{ blog.title }}</strong>
          <div class="mb-1 text-muted">{{ blog.pub_date_pretty }}</div>
          <p class="card-text mb-auto">{{ blog.body_summary }}</p>
          <a href="{% url 'blog:blog_details' blog_id=blog.id %}" class="stretched-link">ادامه مطلب</a>
        </div>
        <br>
        <div class="col-auto d-none d-lg-block">
          <img src="{{ blog.image.url }}" alt='تصویر' width="200" height="250" />
        </div>
      </div>
    </div>

{% endfor %}

  </div>
</div>
{% endblock %}

jobs/templates/jobs/home.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.6">
    <title>My portfolio website</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.4/examples/album/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/4.4/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/4.4/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/4.4/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="manifest" href="/docs/4.4/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="/docs/4.4/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">
    <link rel="icon" href="/docs/4.4/assets/img/favicons/favicon.ico">
    <meta name="msapplication-config" content="/docs/4.4/assets/img/favicons/browserconfig.xml">
    <meta name="theme-color" content="#563d7c">


    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
    <!-- Custom styles for this template -->
    <!--  <link href="album.css" rel="stylesheet">-->
</head>


<body>
<header>


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">امید هاشم زاده</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link active" href="#">صفحه اصلی <span class="sr-only">(current)</span></a>
                <a class="nav-item nav-link" href="{% url 'blog:blog_list' %}">بلاگ</a>
                <a class="nav-item nav-link" href="/static/resume.pdf">رزومه</a>
                <a class="nav-item nav-link disabled" href="#" tabindex="-1" aria-disabled="true">ثبت سفارش</a>
            </div>
        </div>
    </nav>


    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4 class="text-white">About</h4>
                    <p class="text-muted">Add some information about the album below, the author, or any other
                        background context. Make it a few sentences long so folks can pick up some informative tidbits.
                        Then, link them off to some social networking sites or contact information.</p>
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                    <h4 class="text-white">Contact</h4>
                    <ul class="list-unstyled">
                        <li><a href="#" class="text-white">Follow on Twitter</a></li>
                        <li><a href="#" class="text-white">Like on Facebook</a></li>
                        <li><a href="#" class="text-white">Email me</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

</header>

<main role="main">

    <section class="jumbotron text-center">
        <div class="container">
            <h1>امید هاشم زاده</h1>
            <p class="lead text-muted">
                سلام. من امید هاشم زاده هستم. برنامه نویس و طراح وب سایت.
                این وب سایت یک نمونه کار ساده و اولیه می باشد. جهت اطلاعات بیشتر، رزومه بنده را مشاهده نمایید.
            </p>
            <p>
                <a href="https://t.me/omidh2007" class="btn btn-primary my-2">ارتباط با من در تلگرام</a>
                <a href="mailto:omidh2015@gmail.com" class="btn btn-secondary my-2">ارتباط با من از طریق ایمیل</a>
            </p>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">


            <div class="row">
                {% if jobs %}

                {% for job in jobs %}

                <div class="col-md-4">
                    <div class="card mb-4 shadow-sm">
                        <!--            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>-->
                        <img src="{{ job.picture.url }}"/>
                        <div class="card-body">
                            <p class="card-text">{{ job.summary }}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                                    <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                                </div>
                                <small class="text-muted">پست نمونه</small>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
                {% endif %}
            </div>


        </div>
    </div>

</main>

<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Back to top</a>
        </p>
        <p> &copy; Copyright: Omid Hashemzadeh {% now 'Y' %}</p>
    </div>
</footer>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>


<!--    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>-->


<!--<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>-->
<!--      <script>window.jQuery || document.write('<script src="/docs/4.4/assets/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="/docs/4.4/dist/js/bootstrap.bundle.min.js" integrity="sha384-6khuMg9gaYr5AxOqhkVIODVIvm9ynTT5J4V1cfthmT+emCG6yVmEZsRHdxlotUnm" crossorigin="anonymous"></script></body>-->
</html>

templates/_base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Jekyll v3.8.6">
  <title>{% block title %} My portfolio website {% endblock %}</title>

  <link rel="canonical" href="https://getbootstrap.com/docs/4.4/examples/album/">

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <!-- Favicons -->
  <link rel="apple-touch-icon" href="/docs/4.4/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
  <link rel="icon" href="/docs/4.4/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
  <link rel="icon" href="/docs/4.4/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
  <link rel="manifest" href="/docs/4.4/assets/img/favicons/manifest.json">
  <link rel="mask-icon" href="/docs/4.4/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">
  <link rel="icon" href="/docs/4.4/assets/img/favicons/favicon.ico">
  <meta name="msapplication-config" content="/docs/4.4/assets/img/favicons/browserconfig.xml">
  <meta name="theme-color" content="#563d7c">


  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      -ms-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>
  <!-- Custom styles for this template -->
  <!--  <link href="album.css" rel="stylesheet">-->
</head>




<body>
<header>


  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">امید هاشم زاده</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link active" href="#">صفحه اصلی <span class="sr-only">(current)</span></a>
        <a class="nav-item nav-link" href="{% url 'blog:blog_list' %}">بلاگ</a>
        <a class="nav-item nav-link" href="/static/resume.pdf">رزومه</a>
        <a class="nav-item nav-link disabled" href="#" tabindex="-1" aria-disabled="true">ثبت سفارش</a>
      </div>
    </div>
  </nav>



  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Contact</h4>
          <ul class="list-unstyled">
            <li><a href="#" class="text-white">Follow on Twitter</a></li>
            <li><a href="#" class="text-white">Like on Facebook</a></li>
            <li><a href="#" class="text-white">Email me</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

</header>

<main role="main">

<!--  <section class="jumbotron text-center">-->
<!--    <div class="container">-->
<!--      <h1>امید هاشم زاده</h1>-->
<!--      <p class="lead text-muted">سلام. من امید هاشم زاده هستم. برنامه نویس و طراح وب سایت.</p>-->
<!--      <p>-->
<!--        <a href="https://t.me/omidh2007" class="btn btn-primary my-2">ارتباط با من در تلگرام</a>-->
<!--        <a href="mailto:omidh2015@gmail.com" class="btn btn-secondary my-2">Secondary action</a>-->
<!--      </p>-->
<!--    </div>-->
<!--  </section>-->


  {% block content %}

  {% endblock %}

</main>

<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
    <p> &copy; Copyright: Omid Hashemzadeh {% now 'Y' %}</p>
  </div>
</footer>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>


<!--    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>-->


<!--<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>-->
<!--      <script>window.jQuery || document.write('<script src="/docs/4.4/assets/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="/docs/4.4/dist/js/bootstrap.bundle.min.js" integrity="sha384-6khuMg9gaYr5AxOqhkVIODVIvm9ynTT5J4V1cfthmT+emCG6yVmEZsRHdxlotUnm" crossorigin="anonymous"></script></body>-->
</html>